import {approach,approachAngle} from './motion';
import './style.css';
import {B,makeWorld} from './world';
import {spawn,trail,litter,discoveries,height,distance,canWalk,fresh,sanitize,collect,photoFeedback,type Progress,type DiscoveryId,type Point} from './rules';
const paths:Record<string,string>={mountain:'M3 19 10 6l4 7 3-5 5 11H3Z M8 10l2 3 2-3',camera:'M8 5 10 3h4l2 2h4v15H4V5h4Z M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',map:'m3 5 6-2 6 2 6-2v16l-6 2-6-2-6 2V5Z M9 3v16 M15 5v16',leaf:'M20 3C7 2 2 9 5 16s15 5 15-13Z M4 21 16 8',waves:'M2 7q3-4 6 0t6 0 6 0 M2 12q3-4 6 0t6 0 6 0 M2 17q3-4 6 0t6 0 6 0',compass:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z m-6-4-3 7-5 1 3-7 5-1Z',arrow:'M4 12h16 M14 6l6 6-6 6',check:'m5 12 4 4L20 5',close:'m6 6 12 12 M6 18 18 6',pause:'M8 5v14 M16 5v14',sun:'M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0Z M12 1v3 M12 20v3 M1 12h3 M20 12h3 M4 4l2 2 M18 18l2 2 M4 20l2-2 M18 6l2-2',book:'M3 3h7l2 2 2-2h7v17h-7l-2 2-2-2H3V3Z M12 5v17',volume:'M3 9h4l5-5v16l-5-5H3V9Z M16 8q6 4 0 8 M18 4q10 8 0 16',help:'M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0Z M9 8c0-4 7-4 7 0 0 3-4 3-4 6 M12 17v1',target:'M20 12a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z M12 1v6 M12 17v6 M1 12h6 M17 12h6'};
const icon=(name:string)=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"><path d="${paths[name]??paths.compass}"/></svg>`;
const $=<T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
$('app').innerHTML=`<canvas id="world" aria-label="Mundo 3D de Forestín. Usa WASD o flechas para caminar y arrastra para mirar." tabindex="0"></canvas>
<div id="shade"></div><header><div class="brand"><span class="brand-icon">${icon('leaf')}</span><div>FORESTÍN<span>EXPLORA CHILE</span></div></div><div class="location">${icon('mountain')}<span>TORRES DEL PAINE</span><i></i> PATAGONIA</div><div class="top-tools"><button id="sound" class="icon-button" aria-label="Activar sonido" title="Sonido">${icon('volume')}</button><button id="pause" class="icon-button" aria-label="Pausar" title="Pausa">${icon('pause')}</button></div></header>
<main id="welcome"><div class="eyebrow"><span></span> EXPEDICIÓN 01 · CHILE</div><h1>El sur<br>te espera<span>.</span></h1><p>Un sendero. Mil descubrimientos.<br>Explora la Patagonia con Forestín y deja<br class="desktop"> una huella más ligera.</p><button id="start" class="primary">Preparando el paisaje… <span class="spinner"></span></button><div class="welcome-foot">${icon('compass')} A tu ritmo · 4 descubrimientos</div></main>
<div id="intro-caption"><span>50°56′ S · 73°24′ O</span><strong>Donde empieza el asombro.</strong><small>Una interpretación de Torres del Paine</small></div>
<div id="hud" hidden><button id="quest" class="quest"><span class="quest-symbol">${icon('compass')}</span><span><small>TU PRÓXIMO DESCUBRIMIENTO</small><strong id="quest-title">Descubre el mirador</strong><span id="quest-distance"></span></span><span class="quest-arrow">›</span></button><div id="waypoint"><span>◇</span><small id="waypoint-distance"></small></div><div class="bottom-left"><button id="guide" class="guide">${icon('compass')}<span>Seguir sendero</span></button><span class="control-hint"><kbd>W A S D</kbd> caminar <b>·</b> arrastra para mirar</span></div><div id="joystick" aria-label="Joystick para caminar"><div id="stick"></div></div><div class="bottom-right"><button id="recenter" class="round small" aria-label="Recentrar cámara">${icon('target')}</button><button id="map" class="round" aria-label="Abrir mapa">${icon('map')}<span>Mapa</span></button><button id="passport" class="round" aria-label="Abrir pasaporte">${icon('book')}<span id="stamp-count">0 / 4</span></button><button id="photo" class="round" aria-label="Abrir cámara">${icon('camera')}<span>Cámara</span></button></div><button id="action" class="primary contextual" hidden></button><div id="save-status">Guardado en este dispositivo</div></div>
<div id="photo-hud" hidden><div class="photo-title">${icon('camera')} OBSERVATORIO DE FAUNA <button id="close-photo" class="icon-button" aria-label="Salir de cámara">${icon('close')}</button></div><div class="viewfinder"><i></i><i></i><i></i><i></i><span>+</span></div><div class="photo-bottom"><p id="photo-feedback"></p><button id="shutter" aria-label="Tomar fotografía"><span></span></button><small>Arrastra para encuadrar · conserva la distancia</small></div></div>
<div id="toast" role="status" aria-live="polite"></div><dialog id="panel"><div id="panel-content"></div></dialog><div id="flash"></div><footer id="version">EXPEDICIÓN PAINE <span>·</span> PROTOTIPO 0.9</footer>`;
const canvas=$<HTMLCanvasElement>('world'),panel=$<HTMLDialogElement>('panel');
let progress:Progress=fresh();try{progress=sanitize(JSON.parse(localStorage.getItem('forestin.web.v1')||'null'));}catch{}
let world:ReturnType<typeof makeWorld>;let started=false,paused=false,photoMode=false,autoWalk=false,yaw=-.14,pitch=.28,time=0,last=performance.now(),saveClock=0,guideIndex=0,photoValid=false,photoImage='';let moving=0,photoClock=0,uiClock=0,frameAccepted=0,cameraCheckAt=0,cameraFraction=1;let actionKey="";let contextLost=false;let viewYaw=yaw,viewPitch=pitch;let walkVelocity={x:0,z:0};
const keys=new Set<string>();let joy={x:0,y:0};let drag:{id:number;x:number;y:number}|null=null;
function resetInput(){walkVelocity={x:0,z:0};keys.clear();joy={x:0,y:0};$('stick').style.transform='translate(0,0)';drag=null;}
function toast(text:string){$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=window.setTimeout(()=>$('toast').classList.remove('show'),3800);}let toastTimer=0;
function save(){try{localStorage.setItem('forestin.web.v1',JSON.stringify(progress));$('save-status').textContent='Guardado en este dispositivo';}catch{$('save-status').textContent='Progreso de esta sesión';}}
function target(){return discoveries.find(d=>!progress.discovered.includes(d.id));}
function refresh(){const d=target();$('quest-title').textContent=d?d.short:'¡Expedición completada!';$('stamp-count').textContent=`${progress.discovered.length} / 4`;world.rubbish.forEach((m,i)=>m.setEnabled(!progress.collected.includes(i)));world.markers.forEach((m,i)=>m.setEnabled(!progress.discovered.includes(discoveries[i].id)&&discoveries[i].id!=='guanaco'));save();}
function award(id:DiscoveryId){if(progress.discovered.includes(id))return;progress.discovered.push(id);refresh();const d=discoveries.find(d=>d.id===id)!;toast(`Nuevo sello · ${d.title}`);if(progress.discovered.length===4){setTimeout(()=>passport(true),500);}else showDiscovery(id);}
function show(content:string){resetInput();autoWalk=false;updateGuide();paused=true;$('panel-content').innerHTML=`<button id="dialog-close" class="dialog-close icon-button" aria-label="Cerrar">${icon('close')}</button>${content}`;panel.showModal();$('dialog-close').onclick=closePanel;}
function closePanel(){panel.close();paused=false;resetInput();last=performance.now();canvas.focus();}
panel.addEventListener('cancel',e=>{e.preventDefault();closePanel();});panel.addEventListener('click',e=>{if(e.target===panel)closePanel();});
function showDiscovery(id:DiscoveryId){const d=discoveries.find(d=>d.id===id)!;show(`<div class="modal-icon">${icon(d.icon)}</div><div class="eyebrow dark">NUEVO SELLO EN TU PASAPORTE</div><h2>${d.title}</h2><p>${d.fact}</p><div class="discovery-counter">${progress.discovered.length} de 4 descubrimientos</div><button id="continue" class="primary">Seguir explorando ${icon('arrow')}</button>`);$('continue').onclick=closePanel;}
function passport(done=false){show(`<div class="eyebrow dark">CUADERNO DE VIAJE · 01</div><h2>${done?'La naturaleza<br>deja su huella.':'Tu pasaporte<br>patagónico.'}</h2><p>${done?'Cuatro descubrimientos. Un paisaje para recordar. Puedes seguir paseando y tomar más fotografías.':'Cada descubrimiento guarda un pequeño recuerdo de tu expedición.'}</p><div class="stamps">${discoveries.map(d=>`<div class="stamp ${progress.discovered.includes(d.id)?'earned':''}">${icon(d.icon)}<strong>${d.title}</strong><small>${progress.discovered.includes(d.id)?'DESCUBIERTO':'POR DESCUBRIR'}</small></div>`).join('')}</div><div class="passport-footer"><span>${progress.discovered.length} / 4 sellos</span><span>${progress.collected.length} / 3 residuos</span></div>${photoImage?`<img class="memory-photo" src="${photoImage}" alt="Tu fotografía del guanaco"/>`:''}<button id="continue" class="primary">Volver al sendero ${icon('arrow')}</button>`);$('continue').onclick=closePanel;}
function map(){const px=(x:number)=>(x+43)/50*280+20,pz=(z:number)=>(z+58)/101*330+25;const p=progress.position;show(`<div class="eyebrow dark">TU EXPEDICIÓN</div><h2>El sendero del Paine.</h2><p>Descubre a tu ritmo. Los puntos dorados esperan por ti.</p><svg class="trail-map" viewBox="0 0 390 385" role="img" aria-label="Mapa esquemático de la ruta con tu posición"><path d="M320 0C250 80 350 170 300 250S330 330 300 385H390V0Z" fill="#94bbb6"/><path d="M0 45 44 10 92 65 135 22 177 66 220 10 273 62" stroke="#bcc4ac" fill="none" stroke-width="14" stroke-linejoin="round"/><polyline points="${trail.map(t=>`${px(t.x)},${pz(t.z)}`).join(' ')}" fill="none" stroke="#aa9270" stroke-width="4" stroke-dasharray="5 5"/>${discoveries.map(d=>`<circle cx="${px(d.x)}" cy="${pz(d.z)}" r="7" fill="${progress.discovered.includes(d.id)?'#456857':'#c3954c'}"/><text x="${px(d.x)+14}" y="${pz(d.z)+5}" font-size="13" fill="#37473e">${{mirador:'Mirador',guanaco:'Guanacos',lago:'Lago',residuos:'Sendero'}[d.id]}</text>`).join('')}<circle cx="${px(p.x)}" cy="${pz(p.z)}" r="10" fill="#fff"/><circle cx="${px(p.x)}" cy="${pz(p.z)}" r="6" fill="#304e40"/><text x="342" y="345" fill="#426f70" font-size="12" transform="rotate(-90 342 345)">LAGO</text></svg><small class="map-note">Escenario artístico · no es un mapa de excursión real</small><button id="map-guide" class="primary">Guiarme por el sendero ${icon('arrow')}</button>`);$('map-guide').onclick=()=>{closePanel();startGuide();};}
function pauseMenu(){show(`<div class="eyebrow dark">UN MOMENTO EN EL CAMINO</div><h2>Respira Patagonia.</h2><p>Tu expedición se guarda automáticamente en este dispositivo.</p><div class="settings"><button id="day">${icon('sun')} ${progress.night?'Volver a la tarde':'Explorar de noche'}</button><button id="quality">${icon('sun')} Calidad · ${world.quality.label()}</button><button id="help">${icon('help')} Cómo jugar</button><button id="new">${icon('compass')} Nueva expedición</button></div><button id="resume" class="primary">Seguir explorando ${icon('arrow')}</button>`);$('resume').onclick=closePanel;($('quality') as HTMLButtonElement).disabled=world.software;$('quality').onclick=()=>{world.quality.toggle();$('quality').innerHTML=icon('sun')+' Calidad · '+world.quality.label();};$('day').onclick=()=>{progress.night=!progress.night;world.night(progress.night);save();closePanel();};$('help').onclick=()=>{closePanel();show(`<div class="eyebrow dark">GUÍA DE CAMPO</div><h2>El camino es tuyo.</h2><div class="instructions"><p><b>Camina</b> con WASD, las flechas o el joystick izquierdo.</p><p><b>Mira alrededor</b> arrastrando sobre el paisaje. La brújula recentra la cámara.</p><p><b>Descubre</b> al acercarte a los letreros y recoge los tres residuos del camino.</p><p><b>Fotografía</b> a los guanacos desde el sendero. Centra al animal y mantén distancia.</p><p><b>Seguir sendero</b> camina por ti y se detiene en cada encuentro.</p></div>`);};$('new').onclick=()=>{closePanel();show(`<div class="eyebrow dark">VOLVER AL COMIENZO</div><h2>¿Una nueva aventura?</h2><p>Se borrarán los sellos y residuos recogidos de esta expedición.</p><button id="confirm-new" class="primary">Sí, comenzar de nuevo</button><button id="cancel-new" class="text-button">Conservar mi expedición</button>`);$('cancel-new').onclick=closePanel;$('confirm-new').onclick=()=>{progress=fresh();photoImage='';try{localStorage.removeItem('forestin.photo.v1');}catch{}yaw=-.14;pitch=.28;world.night(false);refresh();snapCamera();closePanel();toast('Un nuevo sendero te espera');};};}
function updateGuide(){$('guide').innerHTML=`${icon('compass')}<span>${autoWalk?'Detener paseo':'Seguir sendero'}</span>`;$('guide').classList.toggle('active',autoWalk);}
function startGuide(){let best=Infinity;guideIndex=0;trail.forEach((p,i)=>{const dist=distance(p,progress.position);if(dist<best){best=dist;guideIndex=i;}});if(best<2.8)guideIndex=Math.min(guideIndex+1,trail.length-1);autoWalk=true;updateGuide();toast('Forestín seguirá el sendero. Puedes detenerlo cuando quieras.');}
function stopGuide(){if(!autoWalk)return;autoWalk=false;updateGuide();}
function snapCamera(){viewYaw=yaw;viewPitch=pitch;cameraCheckAt=0;cameraFraction=1;const p=progress.position;world.player.position.set(p.x,height(p.x,p.z),p.z);world.camera.position.copyFrom(cameraPosition());lookCamera();}
function cameraPosition(){const p=progress.position,back=world.mobile?9:7.8,side=world.mobile?2.2:1.65;return new B.Vector3(p.x+Math.sin(viewYaw)*(photoMode?0:back)+(photoMode?0:Math.cos(viewYaw)*side),height(p.x,p.z)+(photoMode?2.45:world.mobile?3.4+viewPitch*5:2.8+viewPitch*3),p.z+Math.cos(viewYaw)*(photoMode?0:back)-(photoMode?0:Math.sin(viewYaw)*side));}
function lookCamera(){const p=progress.position;if(photoMode){world.camera.setTarget(world.camera.position.add(new B.Vector3(-Math.sin(viewYaw)*Math.cos(viewPitch),Math.sin(viewPitch),-Math.cos(viewYaw)*Math.cos(viewPitch))));}else{world.camera.setTarget(new B.Vector3(p.x-Math.sin(viewYaw)*4,height(p.x,p.z)+(world.mobile?3.3:2.5),p.z-Math.cos(viewYaw)*4));}}
function togglePhoto(){photoMode=!photoMode;stopGuide();resetInput();$('photo-hud').hidden=!photoMode;$('hud').hidden=photoMode;world.player.setEnabled(!photoMode);if(photoMode){const p=progress.position,a=[...world.animals].sort((a,b)=>distance(p,a.position)-distance(p,b.position))[0];const aim=world.animalFocus(a);const cam=cameraPosition();yaw=Math.atan2(cam.x-aim.x,cam.z-aim.z);pitch=Math.atan2(aim.y-cam.y,Math.hypot(aim.x-cam.x,aim.z-cam.z));}else pitch=.28;snapCamera();}
function testPhoto(){const camera=world.camera,scene=world.scene,rect=document.querySelector('.viewfinder')!.getBoundingClientRect(),canvasRect=canvas.getBoundingClientRect(),w=world.engine.getRenderWidth(),h=world.engine.getRenderHeight();const candidates=world.animals.map(animal=>{const a=animal.position,aim=world.animalFocus(animal),projected=B.Vector3.Project(aim,B.Matrix.Identity(),scene.getTransformMatrix(),camera.viewport.toGlobal(w,h));const px=canvasRect.left+projected.x/w*canvasRect.width,py=canvasRect.top+projected.y/h*canvasRect.height;const inFrame=projected.z>0&&projected.z<1&&px>rect.left&&px<rect.right&&py>rect.top&&py<rect.bottom;const delta=aim.subtract(camera.position);const hit=scene.pickWithRay(new B.Ray(camera.position,delta.normalizeToNew(),delta.length()+.4),mesh=>!!(mesh.metadata?.occluder||mesh.metadata?.animal),false);const visible=!!hit?.pickedMesh&&animal.getChildMeshes().includes(hit.pickedMesh);const feedback=photoFeedback(distance(progress.position,a),inFrame,visible);return {feedback,valid:feedback.startsWith('Buen'),score:Math.hypot(px-(rect.left+rect.width/2),py-(rect.top+rect.height/2))};});candidates.sort((a,b)=>Number(b.valid)-Number(a.valid)||a.score-b.score);const selected=candidates[0];photoValid=selected.valid;$('photo-feedback').textContent=selected.feedback;$('shutter').classList.toggle('ready',photoValid);}
function takePhoto(){testPhoto();if(!photoValid){toast($('photo-feedback').textContent||'Busca un guanaco');return;}world.render();try{photoImage=canvas.toDataURL('image/jpeg',.72);localStorage.setItem('forestin.photo.v1',photoImage);}catch{}$('flash').classList.add('active');setTimeout(()=>$('flash').classList.remove('active'),180);togglePhoto();if(!progress.discovered.includes('guanaco'))award('guanaco');else{toast('Fotografía guardada en tu pasaporte');passport();}}
let action:()=>void=()=>{};
function updateAction(){const nearby=litter.findIndex((p,i)=>!progress.collected.includes(i)&&distance(p,progress.position)<2.6);const d=discoveries.find(d=>(d.id==='mirador'||d.id==='lago')&&!progress.discovered.includes(d.id)&&distance(d,progress.position)<4.5);const key=nearby>=0?'litter:'+nearby+':'+progress.collected.length:d?.id??'';if(key===actionKey)return;actionKey=key;if(nearby>=0){$('action').hidden=false;$('action').innerHTML=`${icon('leaf')} Recoger residuo · ${progress.collected.length}/3`;action=()=>{if(collect(progress,nearby)){refresh();if(progress.collected.length===3){if(progress.discovered.length===4)passport(true);else showDiscovery('residuos');}else toast(`Sendero más limpio · ${progress.collected.length} de 3`);}};}else if(d){$('action').hidden=false;$('action').innerHTML=`${icon(d.icon)} Descubrir ${d.id==='lago'?'el lago':'el mirador'}`;action=()=>award(d.id);}else{$('action').hidden=true;action=()=>{};}}
function allowed(p:Point){return canWalk(p)&&!world.animals.some(a=>distance(p,a.position)<1.05)&&!world.blockers.some(b=>distance(p,b)<b.r+.32);}
function frame(){const now=performance.now();if(document.hidden||contextLost||paused){last=now;return;}if(world.mobile&&now-frameAccepted<32)return;frameAccepted=now;const rawMs=now-last,dt=Math.min(.12,rawMs/1000);last=now;world.quality.sample(rawMs);photoClock+=dt;uiClock+=dt;const updateUI=uiClock>=.12;if(updateUI)uiClock=0;if(!paused){time+=dt;moving=0;if(started&&!photoMode){let x=0,z=0;if(autoWalk){const goal=trail[guideIndex];const dx=goal.x-progress.position.x,dz=goal.z-progress.position.z,dist=Math.hypot(dx,dz);if(dist<.8){stopGuide();toast(guideIndex===2?'Estás en el mirador. Descubre el paisaje.':guideIndex===3&&!progress.discovered.includes('guanaco')?'Hay guanacos cerca. Prueba la cámara.':guideIndex===trail.length-1?'Llegaste al final del sendero. Sigue explorando.':'Una pausa para descubrir. Pulsa Seguir sendero para continuar.');}else{x=dx/dist;z=dz/dist;const goalYaw=Math.atan2(-x,-z);yaw+=Math.atan2(Math.sin(goalYaw-yaw),Math.cos(goalYaw-yaw))*Math.min(1,dt*1.5);}}else{let ix=(keys.has('d')||keys.has('ArrowRight')?1:0)-(keys.has('a')||keys.has('ArrowLeft')?1:0)+joy.x,iy=(keys.has('w')||keys.has('ArrowUp')?1:0)-(keys.has('s')||keys.has('ArrowDown')?1:0)-joy.y;const len=Math.max(1,Math.hypot(ix,iy));ix/=len;iy/=len;x=Math.cos(yaw)*ix-Math.sin(yaw)*iy;z=-Math.sin(yaw)*ix-Math.cos(yaw)*iy;}if(!world.mobile&&!autoWalk){const response=Math.hypot(x,z)>.05?10:14;walkVelocity.x=approach(walkVelocity.x,x,dt,response);walkVelocity.z=approach(walkVelocity.z,z,dt,response);x=walkVelocity.x;z=walkVelocity.z;}else{walkVelocity.x=x;walkVelocity.z=z;}moving=Math.min(1,Math.hypot(x,z));if(moving>.05){const p=progress.position,steps=Math.ceil(dt/.04),step=dt*3.9/steps;for(let i=0;i<steps;i++){const nx={x:p.x+x*step,z:p.z};if(allowed(nx))p.x=nx.x;const nz={x:p.x,z:p.z+z*step};if(allowed(nz))p.z=nz.z;}const rotation=Math.atan2(-x,-z);world.player.rotation.y+=Math.atan2(Math.sin(rotation-world.player.rotation.y),Math.cos(rotation-world.player.rotation.y))*Math.min(1,dt*10);}world.player.position.set(progress.position.x,height(progress.position.x,progress.position.z),progress.position.z);if(updateUI)updateAction();}
 if(!started){yaw=-.14+Math.sin(time*.08)*.08;}
 viewYaw=world.mobile?yaw:approachAngle(viewYaw,yaw,dt,photoMode?17:12);viewPitch=world.mobile?pitch:approach(viewPitch,pitch,dt,14);
 const desired=cameraPosition();if(!photoMode){const p=world.player.position.add(new B.Vector3(0,1.8,0)),delta=desired.subtract(p);if(!world.mobile||now-cameraCheckAt>100){cameraCheckAt=now;const hit=world.scene.pickWithRay(new B.Ray(p,delta.normalizeToNew(),delta.length()),m=>!!m.metadata?.occluder,false);cameraFraction=hit?.hit&&hit.pickedPoint?Math.max(.12,(B.Vector3.Distance(p,hit.pickedPoint)-.45)/delta.length()):1;}if(cameraFraction<1)desired.copyFrom(p.add(delta.scale(cameraFraction)));desired.y=Math.max(desired.y,height(desired.x,desired.z)+.7);}
 world.camera.position=B.Vector3.Lerp(world.camera.position,desired,photoMode?1:1-Math.exp(-dt*8));lookCamera();world.animate(time,moving,dt);world.scene.updateTransformMatrix(true);if(photoMode&&photoClock>=.12){photoClock=0;testPhoto();}if(started){saveClock+=dt;if(saveClock>4){save();saveClock=0;}}
 const d=target();if(updateUI&&d){const destination=d.id==='residuos'?(litter.find((_,i)=>!progress.collected.includes(i))??d):d;$('quest-distance').textContent=`${Math.round(distance(progress.position,destination))} m · ${d.id==='residuos'?progress.collected.length+'/3 residuos':'abre para ver la ruta'}`;const p=B.Vector3.Project(new B.Vector3(destination.x,height(destination.x,destination.z)+3.5,destination.z),B.Matrix.Identity(),world.scene.getTransformMatrix(),world.camera.viewport.toGlobal(world.engine.getRenderWidth(),world.engine.getRenderHeight()));const visible=started&&!photoMode&&p.z>0&&p.z<1&&p.x>0&&p.x<world.engine.getRenderWidth()&&p.y>100&&p.y<world.engine.getRenderHeight()*.8;$('waypoint').style.display=visible?'flex':'none';$('waypoint').style.left=(p.x/world.engine.getRenderWidth()*100)+'%';$('waypoint').style.top=(p.y/world.engine.getRenderHeight()*100)+'%';$('waypoint-distance').textContent=Math.round(distance(progress.position,destination))+' m';}else if(!d){$('waypoint').style.display='none';$('quest-distance').textContent='Tus cuatro sellos están en el pasaporte';}}
 world.render();}
$('start').setAttribute('disabled','');
try{world=makeWorld(canvas);world.night(progress.night);snapCamera();refresh();try{photoImage=localStorage.getItem('forestin.photo.v1')||'';}catch{}const ready=()=>{$('start').removeAttribute('disabled');$('start').innerHTML=`${progress.discovered.length||distance(progress.position,spawn)>1?'Continuar expedición':'Comenzar expedición'} ${icon('arrow')}`;world.engine.runRenderLoop(frame);};if(world.software)ready();else world.scene.executeWhenReady(ready);}catch(error){console.error(error);$('start').textContent='Reintentar';$('start').removeAttribute('disabled');$('welcome').querySelector('p')!.textContent='No pudimos iniciar el paisaje 3D. Prueba recargar en un navegador con WebGL.';$('start').onclick=()=>location.reload();}
$('start').addEventListener('click',()=>{if(!world)return;started=true;$('welcome').hidden=true;$('intro-caption').hidden=true;$('hud').hidden=false;$('shade').classList.add('playing');document.body.classList.add('playing');canvas.focus();toast('Sigue el sendero o explora libremente. El mirador te espera.');});
$('guide').onclick=()=>autoWalk?stopGuide():startGuide();$('quest').onclick=()=>target()?map():passport();$('map').onclick=map;$('passport').onclick=()=>passport();$('pause').onclick=()=>{if(started)pauseMenu();};$('photo').onclick=togglePhoto;$('close-photo').onclick=togglePhoto;$('shutter').onclick=takePhoto;$('action').onclick=()=>action();$('recenter').onclick=()=>{yaw=world.player.rotation.y;pitch=.28;};
let audioCtx:AudioContext|null=null,audioGain:GainNode|null=null,soundOn=false;
$('sound').onclick=()=>{if(!audioCtx){audioCtx=new AudioContext();const buffer=audioCtx.createBuffer(1,audioCtx.sampleRate*3,audioCtx.sampleRate),data=buffer.getChannelData(0);let smooth=0;for(let i=0;i<data.length;i++){smooth=(smooth+Math.random()*.08-.04)*.98;data[i]=smooth;}const source=audioCtx.createBufferSource();source.buffer=buffer;source.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;audioGain=audioCtx.createGain();audioGain.gain.value=0;source.connect(filter).connect(audioGain).connect(audioCtx.destination);source.start();}soundOn=!soundOn;void audioCtx.resume();audioGain!.gain.setTargetAtTime(soundOn?.32:0,audioCtx.currentTime,.4);$('sound').classList.toggle('active',soundOn);$('sound').setAttribute('aria-label',soundOn?'Silenciar sonido':'Activar sonido');toast(soundOn?'Viento de la Patagonia activado':'Sonido desactivado');};
window.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(paused||!started)return;if(e.key==='Escape'){if(photoMode)togglePhoto();else pauseMenu();return;}if(e.key.toLowerCase()==='c'){togglePhoto();return;}if(e.key===' '){if(photoMode)takePhoto();else action();return;}const key=e.key.length===1?e.key.toLowerCase():e.key;keys.add(key);if(['w','a','s','d','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key))stopGuide();});window.addEventListener('keyup',e=>keys.delete(e.key.length===1?e.key.toLowerCase():e.key));
canvas.addEventListener('pointerdown',e=>{if(paused||!started||drag)return;drag={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;yaw-=(e.clientX-drag.x)*.006;pitch=Math.max(photoMode?-.65:.08,Math.min(photoMode?.65:.85,pitch-(e.clientY-drag.y)*.004));drag.x=e.clientX;drag.y=e.clientY;});function endLook(e:PointerEvent){if(drag?.id===e.pointerId)drag=null;}canvas.addEventListener('pointerup',endLook);canvas.addEventListener('pointercancel',endLook);canvas.addEventListener('lostpointercapture',endLook);
const joystick=$('joystick');let joyId:number|null=null;function setJoy(e:PointerEvent){const rect=joystick.getBoundingClientRect();let x=(e.clientX-rect.left-rect.width/2)/40,y=(e.clientY-rect.top-rect.height/2)/40;const len=Math.max(1,Math.hypot(x,y));x/=len;y/=len;joy=Math.hypot(x,y)<.12?{x:0,y:0}:{x,y};$('stick').style.transform=`translate(${x*37}px,${y*37}px)`;}
joystick.addEventListener('pointerdown',e=>{if(paused||photoMode||joyId!==null)return;joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);stopGuide();setJoy(e);});joystick.addEventListener('pointermove',e=>{if(e.pointerId===joyId)setJoy(e);});function endJoy(){joyId=null;joy={x:0,y:0};$('stick').style.transform='translate(0,0)';}const endJoyPointer=(e:PointerEvent)=>{if(e.pointerId===joyId)endJoy();};joystick.addEventListener('pointerup',endJoyPointer);joystick.addEventListener('pointercancel',endJoyPointer);joystick.addEventListener('lostpointercapture',endJoyPointer);
window.addEventListener('blur',()=>{resetInput();endJoy();stopGuide();});document.addEventListener('visibilitychange',()=>{resetInput();endJoy();stopGuide();save();last=performance.now();if(document.hidden)world?.engine.stopRenderLoop(frame);else if(world&&!contextLost)world.engine.runRenderLoop(frame);if(audioCtx){if(document.hidden)void audioCtx.suspend();else if(soundOn)void audioCtx.resume();}});function resizeWorld(){world?.quality.resize();world?.engine.resize();}window.addEventListener('resize',resizeWorld);window.visualViewport?.addEventListener('resize',resizeWorld);window.addEventListener('pagehide',()=>{save();resetInput();endJoy();world?.engine.stopRenderLoop(frame);});window.addEventListener('pageshow',()=>{last=performance.now();if(world&&!document.hidden&&!contextLost)world.engine.runRenderLoop(frame);});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();contextLost=true;save();resetInput();endJoy();world?.engine.stopRenderLoop(frame);toast('Recuperando el paisaje… Tu avance está guardado.');});canvas.addEventListener('webglcontextrestored',()=>{contextLost=false;last=performance.now();resizeWorld();if(!document.hidden)world?.engine.runRenderLoop(frame);toast('El sendero está listo para continuar.');});
