// A real polygon renderer for environments without WebGL. It shares geometry,
// camera, picking and game rules; the normal path uses hardware Babylon rendering.
import {Color3,Scene,Mesh,StandardMaterial,Vector3,Matrix} from './babylon';
type Face={p:number[];depth:number;color:string};
export function softwareRenderer(canvas:HTMLCanvasElement,scene:Scene,onSize:(w:number,h:number)=>void){const ctx=canvas.getContext('2d')!;let previous=0;const cache=new WeakMap<Mesh,{matrix:string;positions:Float32Array;normals:Float32Array}>();
 return (night:boolean)=>{if(performance.now()-previous<85)return;previous=performance.now();const w=Math.min(canvas.clientWidth,900),h=Math.round(canvas.clientHeight*w/canvas.clientWidth);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;onSize(w,h);}const sky=ctx.createLinearGradient(0,0,0,h*.75);sky.addColorStop(0,night?'#101f37':'#669bcb');sky.addColorStop(.7,night?'#263a50':'#b7cdd0');sky.addColorStop(1,night?'#34484e':'#e3e3c6');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);
 if(!night){ctx.fillStyle='#fbf4dc4d';for(let i=0;i<7;i++){ctx.beginPath();ctx.ellipse(w*(.13+i*.17),h*(.13+Math.sin(i*4)*.06),w*.11,h*.026,0,0,Math.PI*2);ctx.fill();}}
 const view=scene.getTransformMatrix().m,faces:Face[]=[],light=new Vector3(-.5,1,-.35).normalize();const camera=scene.activeCamera!;
 for(const abstract of scene.meshes){if(abstract.name==='helmet lettering'||abstract.name==='low shrub' || (abstract.name==='golden grasses' && canvas.clientWidth<500))continue;if(!(abstract instanceof Mesh)||!abstract.isEnabled()||!abstract.isVisible||abstract.name==='sky'||abstract.name==='ripple')continue;const mesh=abstract,positions=mesh.getVerticesData('position'),indices=mesh.getIndices();if(!positions||!indices)continue;mesh.computeWorldMatrix(true);const wm=mesh.getWorldMatrix().m,key=Array.from(wm).join(',');let data=cache.get(mesh);if(!data||data.matrix!==key){const wp=new Float32Array(positions.length),normals=new Float32Array(positions.length),rawNormals=mesh.getVerticesData('normal');for(let i=0;i<positions.length;i+=3){const x=positions[i],y=positions[i+1],z=positions[i+2];wp[i]=x*wm[0]+y*wm[4]+z*wm[8]+wm[12];wp[i+1]=x*wm[1]+y*wm[5]+z*wm[9]+wm[13];wp[i+2]=x*wm[2]+y*wm[6]+z*wm[10]+wm[14];if(rawNormals){const n=Vector3.TransformNormal(new Vector3(rawNormals[i],rawNormals[i+1],rawNormals[i+2]),mesh.getWorldMatrix()).normalize();normals.set([n.x,n.y,n.z],i);}}data={matrix:key,positions:wp,normals};cache.set(mesh,data);}
 const n=positions.length/3,screen=new Float32Array(n*3);for(let i=0;i<n;i++){const x=data.positions[i*3],y=data.positions[i*3+1],z=data.positions[i*3+2],cw=x*view[3]+y*view[7]+z*view[11]+view[15];screen[i*3]=(x*view[0]+y*view[4]+z*view[8]+view[12])/cw*w*.5+w*.5;screen[i*3+1]=h*.5-(x*view[1]+y*view[5]+z*view[9]+view[13])/cw*h*.5;screen[i*3+2]=cw;}
 const material=mesh.material as StandardMaterial,base=material?.diffuseColor??new Color3(.7,.7,.6),colors=mesh.getVerticesData('color');for(let i=0;i<indices.length;i+=3){const a=indices[i],b=indices[i+1],c=indices[i+2],ax=screen[a*3],ay=screen[a*3+1],bx=screen[b*3],by=screen[b*3+1],cx=screen[c*3],cy=screen[c*3+1];if(screen[a*3+2]<.12||screen[b*3+2]<.12||screen[c*3+2]<.12||Math.max(ax,bx,cx)<0||Math.min(ax,bx,cx)>w||Math.max(ay,by,cy)<0||Math.min(ay,by,cy)>h)continue;
 const back=data.normals[a*3]*(camera.position.x-data.positions[a*3])+data.normals[a*3+1]*(camera.position.y-data.positions[a*3+1])+data.normals[a*3+2]*(camera.position.z-data.positions[a*3+2]);if(back<0&&mesh.material?.backFaceCulling!==false)continue;const depth=(screen[a*3+2]+screen[b*3+2]+screen[c*3+2])/3;const dot=data.normals[a*3]*light.x+data.normals[a*3+1]*light.y+data.normals[a*3+2]*light.z;const shade=night?.38:.62+Math.max(0,dot)*.48;const fog=Math.min(.72,1-Math.exp(-depth*.002));const rgb=[base.r,base.g,base.b].map((v,k)=>{const color=colors?(colors[a*4+k]+colors[b*4+k]+colors[c*4+k])/3:1;return Math.round(Math.max(0,Math.min(1,v*color*shade*(1-fog)+(night?[.13,.2,.29]:[.64,.76,.77])[k]*fog))*255);});faces.push({p:[ax,ay,bx,by,cx,cy],depth,color:`rgb(${rgb.join(',')})`});}}
 faces.sort((a,b)=>b.depth-a.depth);for(const f of faces){ctx.beginPath();ctx.moveTo(f.p[0],f.p[1]);ctx.lineTo(f.p[2],f.p[3]);ctx.lineTo(f.p[4],f.p[5]);ctx.closePath();ctx.fillStyle=f.color;ctx.strokeStyle=f.color;ctx.lineWidth=.4;ctx.fill();ctx.stroke();}for(const m of scene.meshes){if(!m.metadata?.label||!m.isEnabled()||!m.isVisible)continue;const p=Vector3.Project(m.getAbsolutePosition(),Matrix.Identity(),scene.getTransformMatrix(),camera.viewport.toGlobal(w,h));if(p.z>0&&p.z<1){const dist=Vector3.Distance(camera.position,m.getAbsolutePosition());const size=Math.max(5,Math.min(20,145/dist));ctx.font='bold '+size+'px sans-serif';ctx.textAlign='center';ctx.fillStyle=m.metadata.labelColor??'#56452d';ctx.fillText(m.metadata.label,p.x,p.y+size*.3);}}
 };
}
