import {foliageCluster,foliageSeed} from './foliage';
import {furTufts,furSurface,bootDetails} from './art';
import {wildlifeStep,type WildlifeState} from './wildlife';
import * as B from './babylon';
import {surface,cinematicPipeline,lakeMaterial,skyEnvironment,grassMaterial} from './cinematic';
import {softwareRenderer} from './software';
import {height,distance,distanceToTrail,canWalk,trail,litter,discoveries,type Point} from './rules';
export {B};
export function makeWorld(canvas:HTMLCanvasElement){
 const mobile=matchMedia('(pointer:coarse)').matches;let software=false;let engine:B.Engine;const fallbackSize={renderWidth:canvas.clientWidth,renderHeight:canvas.clientHeight,textureSize:512,deterministicLockstep:false,lockstepMaxSteps:4};try{engine=new B.Engine(canvas,!mobile,{preserveDrawingBuffer:false,stencil:false,antialias:!mobile,powerPreference:mobile?'default':'high-performance'},false);}catch{software=true;engine=new B.NullEngine(fallbackSize);}engine.setHardwareScalingLevel(1);
 const scene=new B.Scene(engine);scene.useRightHandedSystem=true;scene.clearColor=new B.Color4(.58,.76,.85,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.0032;scene.fogColor=new B.Color3(.65,.77,.79);scene.skipPointerMovePicking=true;
 const camera=new B.FreeCamera('explorer camera',new B.Vector3(-5,10,43),scene);camera.minZ=.15;camera.maxZ=800;camera.fov=.9;camera.inputs.clear();scene.activeCamera=camera;
 const hemi=new B.HemisphericLight('sky light',new B.Vector3(0,1,0),scene);hemi.intensity=.58;hemi.groundColor=new B.Color3(.32,.29,.2);
 const sun=new B.DirectionalLight('late afternoon sun',new B.Vector3(.6,-1,.35),scene);sun.position=new B.Vector3(-90,140,-80);sun.intensity=1.65;sun.diffuse=new B.Color3(1,.88,.65);
 const shadow=new B.ShadowGenerator(mobile?512:1536,sun);shadow.usePercentageCloserFiltering=!software&&!mobile;shadow.usePoissonSampling=mobile&&!software;scene.shadowsEnabled=!software;shadow.filteringQuality=B.ShadowGenerator.QUALITY_MEDIUM;shadow.normalBias=.025;shadow.darkness=.25;sun.shadowMinZ=1;sun.shadowMaxZ=270;
 function cast(m:B.AbstractMesh){if(!mobile||/^(shirt|head|trousers|sleeve|trouser thigh|boot|guanaco torso|long neck|guanaco upper leg|lenga trunk|granite)/.test(m.name))shadow.addShadowCaster(m);}
 const blockers:{x:number;z:number;r:number}[]=[];
 function mat(name:string,color:string){const m=new B.StandardMaterial(name,scene);m.diffuseColor=B.Color3.FromHexString(color);m.specularColor=new B.Color3(.05,.05,.04);return m;}
 const mats={eye:mat('glossy dark eyes','#101919'),cream:mat('guanaco ivory undercoat','#e2dcc5'),animalNose:mat('guanaco muzzle grey','#565249'),pocket:mat('uniform pocket flaps','#918c73'),fur:mat('warm brown fur','#b48240'),muzzle:mat('cream muzzle','#d8aa61'),nose:mat('nose and eyes','#242522'),shirt:mat('khaki ranger shirt','#a39d82'),pants:mat('brown ranger trousers','#655348'),boots:mat('leather boots','#293735'),helmet:mat('ivory details','#eee8d6'),hardhat:mat('green Forestin helmet','#429449'),gloves:mat('ranger gloves','#dad4ad'),pack:mat('canvas backpack','#7a7558'),strap:mat('canvas straps','#4c4b34'),leaf:mat('lenga green','#657442'),leaf2:mat('lenga light','#8c9350'),bark:mat('weathered wood','#5f4c32'),rock:mat('granite boulders','#81816f'),white:mat('snow','#e5e9e3'),gold:mat('discovery gold','#f0cf73'),brown:mat('guanaco fur','#a97a4e')};
 function ell(name:string,pos:number[],scale:number[],material:B.Material,parent?:B.TransformNode){const m=B.MeshBuilder.CreateSphere(name,{diameter:1,segments:software?6:parent?(mobile?8:16):(mobile?5:8)},scene);m.position.set(pos[0],pos[1],pos[2]);m.scaling.set(scale[0],scale[1],scale[2]);m.material=material;m.parent=parent??null;return m;}
 function box(name:string,pos:number[],scale:number[],material:B.Material,parent?:B.TransformNode){const m=B.MeshBuilder.CreateBox(name,{size:1},scene);m.position.set(...pos as [number,number,number]);m.scaling.set(...scale as [number,number,number]);m.material=material;m.parent=parent??null;return m;}
 const player=new B.TransformNode('Forestín',scene);const body=new B.TransformNode('walking body',scene);body.parent=player;
 ell('shirt',[0,1.24,0],[.89,1,.64],mats.shirt,body);ell('trousers',[0,.79,0],[.78,.45,.58],mats.pants,body);
 ell('head',[0,1.99,.04],[1.0,.85,.8],mats.fur,body);for(const side of [-1,1])ell('muzzle cheek',[side*.17,1.86,-.43],[.5,.41,.44],mats.muzzle,body);ell('nose',[0,2.0,-.665],[.35,.23,.23],mats.nose,body);
 for(const side of [-1,1]){ell('ear',[side*.4,2.12,0],[.24,.28,.17],mats.fur,body);ell('ear inner',[side*.4,2.12,-.07],[.13,.16,.05],mats.boots,body);ell('eye white',[side*.24,2.12,-.35],[.114,.145,.08],mats.fur,body);ell('eye',[side*.24,2.13,-.405],[.11,.14,.065],mats.eye,body);box('tooth',[side*.052,1.69,-.57],[.088,.14,.065],mats.helmet,body);box('backpack strap',[side*.29,1.39,-.26],[.11,.68,.1],mats.strap,body);}
 ell('helmet dome',[0,2.3,0],[1.1,.55,.95],mats.hardhat,body);ell('helmet brim',[0,2.28,-.095],[1.2,.085,1.0],mats.hardhat,body);
 ell('backpack',[0,1.34,.43],[.76,.83,.4],mats.pack,body);ell('backpack pocket',[0,1.16,.65],[.49,.33,.17],mats.strap,body);box('pack patch',[0,1.51,.59],[.18,.19,.018],mats.helmet,body);
 const legs:B.TransformNode[]=[],arms:B.TransformNode[]=[],knees:B.TransformNode[]=[];
 for(const side of [-1,1]){const leg=new B.TransformNode('leg',scene);leg.parent=body;leg.position.set(side*.22,.83,0);ell('trouser thigh',[0,-.15,0],[.37,.37,.42],mats.pants,leg);const knee=new B.TransformNode('knee',scene);knee.parent=leg;knee.position.y=-.3;knees.push(knee);ell('trouser shin',[0,-.16,0],[.31,.35,.35],mats.pants,knee);ell('boot',[0,-.32,-.09],[.38,.28,.59],mats.boots,knee);bootDetails(scene,knee,mats.boots,mats.pack);legs.push(leg);const arm=new B.TransformNode('arm',scene);arm.parent=body;arm.position.set(side*.48,1.62,0);ell('sleeve',[0,-.21,0],[.34,.56,.35],mats.shirt,arm);ell('glove',[0,-.5,-.025],[.28,.34,.28],mats.gloves,arm);ell('glove thumb',[-side*.13,-.48,-.085],[.12,.19,.14],mats.gloves,arm);arms.push(arm);}
 const tail=ell('coipo tail',[0,.5,.64],[.18,.17,1.03],mats.fur,body);tail.rotation.x=.22;
 mats.leaf.backFaceCulling=false;mats.leaf2.backFaceCulling=false;
 const lids:B.Mesh[]=[];
 for(const side of [-1,1]){ell('eye glint',[side*.24-.015,2.16,-.445],[.028,.035,.018],mats.helmet,body);const lid=ell('eyelid',[side*.24,2.135,-.415],[.15,.015,.085],mats.fur,body);lids.push(lid);const brow=ell('eyebrow',[side*.24,2.25,-.36],[.21,.055,.08],mats.boots,body);brow.rotation.z=side*.13;for(let i=0;i<3;i++){const whisker=B.MeshBuilder.CreateTube('whisker',{path:[new B.Vector3(side*.24,1.85,-.53),new B.Vector3(side*(.48+i*.035),1.82+i*.04,-.54)],radius:.005,tessellation:3},scene);whisker.material=mats.boots;whisker.parent=body;}box('shirt pocket',[side*.2,1.4,-.319],[.22,.22,.035],mats.shirt,body);box('pocket flap',[side*.2,1.51,-.347],[.235,.065,.045],mats.pocket,body);box('pack buckle',[side*.22,1.12,.72],[.07,.09,.035],mats.boots,body);}
 box('shirt seam',[0,1.29,-.324],[.014,.48,.025],mats.pack,body);ell('pack flap',[0,1.7,.53],[.7,.22,.35],mats.pack,body);
 for(const side of [-1,1]){const collar=box('shirt collar',[side*.17,1.7,-.27],[.3,.12,.12],mats.shirt,body);collar.rotation.z=side*.38;}
 for(let i=0;i<4;i++)ell('shirt button',[0,1.56-i*.16,-.35],[.04,.04,.026],mats.boots,body);
 const helmetInk=new B.DynamicTexture('Forestin helmet lettering',{width:512,height:128},scene,true);const hc=helmetInk.getContext();hc.clearRect(0,0,512,128);hc.fillStyle='#fff5d9';hc.font='bold 85px Georgia';hc.fillText('Forestín',42,96);helmetInk.hasAlpha=true;helmetInk.update();const helmetLabel=B.MeshBuilder.CreatePlane('helmet lettering',{width:.74,height:.185},scene);helmetLabel.position.set(0,2.45,-.438);helmetLabel.parent=body;const helmetLabelMat=mat('helmet white ink','#ffffff');helmetLabelMat.diffuseTexture=helmetInk;helmetLabelMat.useAlphaFromDiffuseTexture=true;helmetLabelMat.backFaceCulling=false;helmetLabel.material=helmetLabelMat;helmetLabel.metadata={label:'Forestín',labelColor:'#fff5d9'};
 const headRig=new B.TransformNode('head rig',scene);headRig.parent=body;headRig.position.y=1.82;
 const headNames=['head','muzzle cheek','nose','ear','ear inner','eye white','eye','tooth','helmet dome','helmet brim','helmet badge','helmet lettering','eye glint','eyelid','eyebrow','whisker'];body.getChildMeshes().filter(m=>headNames.includes(m.name)).forEach(m=>m.setParent(headRig));headRig.scaling.setAll(1.08);
 furTufts(scene,headRig,new B.Vector3(0,.17,.04),new B.Vector3(.505,.43,.405),software?130:mobile?400:1400,'#b48240','Forestin head fur');
 for(const side of [-1,1])furTufts(scene,headRig,new B.Vector3(side*.17,.04,-.43),new B.Vector3(.25,.205,.22),software?55:mobile?150:450,'#d8aa61','Forestin cheek fur');
 player.getChildMeshes().forEach(m=>{cast(m);m.isPickable=false;});
 // Sky is a real shader sphere, with soft procedural cloud layers.
 B.Effect.ShadersStore['paineSkyVertexShader']='precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;varying vec3 vPosition;void main(){vPosition=position;gl_Position=worldViewProjection*vec4(position,1.0);}';
 B.Effect.ShadersStore['paineSkyFragmentShader']=`precision highp float;varying vec3 vPosition;uniform float night;uniform float time;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec3 d=normalize(vPosition);float h=max(d.y,0.);vec3 col=mix(vec3(.81,.86,.8),vec3(.27,.57,.82),pow(h,.45));vec2 p=d.xz/max(.12,d.y)*2.8+vec2(time*.006,time*.002);float n=noise(p)*.58+noise(p*2.1)*.26+noise(p*4.3)*.16;float cloud=smoothstep(.52,.72,n)*smoothstep(.03,.28,h);col=mix(col,vec3(.98,.95,.86),cloud*.9);float glow=pow(max(0.,dot(d,normalize(vec3(-.6,.48,-.5)))),40.);col+=vec3(.32,.21,.09)*glow;col=mix(col,vec3(.025,.048,.09)+col*.07,night);float stars=step(.9975,hash(floor(d.xz/max(.05,d.y)*700.)))*smoothstep(.15,.4,h);col+=stars*night*.8;gl_FragColor=vec4(col,1.);}`;
 const skyMat=new B.ShaderMaterial('Patagonian sky',scene,{vertex:'paineSky',fragment:'paineSky'},{attributes:['position'],uniforms:['worldViewProjection','night','time']});skyMat.backFaceCulling=false;skyMat.setFloat('night',0);skyMat.setFloat('time',0);skyMat.disableDepthWrite=true;const sky=B.MeshBuilder.CreateSphere('sky',{diameter:1200,segments:24},scene);sky.material=skyMat;sky.isPickable=false;sky.infiniteDistance=true;
 let seed=134;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
 // Shared analytical height field keeps feet, trail and terrain aligned.
 const positions:number[]=[],indices:number[]=[],colors:number[]=[],uvs:number[]=[];const nx=software?45:mobile?96:180,nz=software?50:mobile?110:200;
 for(let j=0;j<=nz;j++)for(let i=0;i<=nx;i++){const x=-180+i*(360/nx),z=-300+j*(400/nz);const y=height(x,z);positions.push(x,y,z);uvs.push((x+180)/360,(z+300)/400);const d=distanceToTrail({x,z});const tint=rand()*.1+Math.sin(x*.31+z*.2)*.04;let c=B.Color3.FromHexString(d<1.6?'#c4b28b':d<2.1?'#a6a077':'#929365');if(y<1.6)c=B.Color3.FromHexString('#97977f');c=c.scale(1+tint);colors.push(c.r,c.g,c.b,1);}
 // Keep world placement RNG identical to desktop after changing only terrain tessellation.
 if(mobile&&!software)for(let i=(nx+1)*(nz+1);i<181*201;i++)rand();
 for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const a=j*(nx+1)+i;indices.push(a,a+nx+1,a+1,a+1,a+nx+1,a+nx+2);}
 const normals:number[]=[];B.VertexData.ComputeNormals(positions,indices,normals,{useRightHandedSystem:true});const ground=new B.Mesh('rolling Patagonian steppe',scene);const vd=new B.VertexData();Object.assign(vd,{positions,indices,normals,colors,uvs});vd.applyToMesh(ground);const groundMat=mat('meadow','#ffffff');groundMat.backFaceCulling=false;ground.material=groundMat;ground.receiveShadows=true;ground.metadata={occluder:true};
 // Build a smooth narrow ribbon along the actual route.
 const paths:B.Vector3[][]=[[],[]];for(let n=0;n<trail.length-1;n++){const a=trail[n],b=trail[n+1],len=Math.hypot(b.x-a.x,b.z-a.z),px=-(b.z-a.z)/len,pz=(b.x-a.x)/len;for(let t=0;t<1;t+=.055){const x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;for(let s=0;s<2;s++){const sign=s?1:-1,xx=x+px*1.35*sign,zz=z+pz*1.35*sign;paths[s].push(new B.Vector3(xx,height(xx,zz)+(software?.32:.07),zz));}}}
 const path=B.MeshBuilder.CreateRibbon('winding trail',{pathArray:paths,sideOrientation:B.Mesh.DOUBLESIDE},scene);path.material=mat('sandy trail','#bca884');path.receiveShadows=true;path.isPickable=false;
 const mountainMat=mat('weathered mountain granite','#ffffff');mountainMat.backFaceCulling=false;
 // Rock spires: irregular radial ridges, not cones.
 function peak(name:string,x:number,z:number,h:number,r:number,salt:number){const p:number[]=[],ind:number[]=[],col:number[]=[],uv:number[]=[],segments=software?20:mobile?24:40,rings=software?15:mobile?18:32;const phase=salt*.71;
 for(let k=0;k<=rings;k++){const t=k/rings;for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2;const channel=Math.pow(.5+.5*Math.sin(a*11+salt+Math.sin(t*6)*.26),5);const ridge=1+Math.sin(a*7+salt)*.15+Math.cos(a*13+salt)*.07+Math.sin(t*24+a*3)*.03-channel*.12;const tower=name.startsWith("Torre");const profile=tower?(t<.24?1-t*1.6:t<.84?.616-(t-.24)*.32:.424*Math.pow((1-t)/.16,.48)):Math.pow(1-t,.72);const radius=r*profile*ridge+(k===rings?.12:0);uv.push(i/segments,t);p.push(x+Math.cos(a)*radius+Math.sin(t*4+phase)*r*.15,h*t-1,z+Math.sin(a)*radius);const snow=!tower&&t>.46&&Math.cos(a+salt)>.05&&channel>.38;const shade=.89+Math.sin(a*9+salt)*.085+Math.sin(t*47+a*3)*.045-channel*.19;const c=B.Color3.FromHexString(snow?'#e3e8e2':t>.78?'#a0a2a1':t>.3?'#778387':'#777e72').scale(shade);col.push(c.r,c.g,c.b,1);}}
 for(let k=0;k<rings;k++)for(let i=0;i<segments;i++){const a=k*segments+i,b=k*segments+(i+1)%segments;ind.push(a,b,a+segments,b,b+segments,a+segments);}const nm:number[]=[];B.VertexData.ComputeNormals(p,ind,nm);if(!name.startsWith('Torre'))for(let v=0;v<p.length/3;v++){const t=(p[v*3+1]+1)/h,slope=Math.abs(nm[v*3+1]);if(t>.4&&slope>.58&&t>.56+Math.sin(p[v*3]*.32+p[v*3+2]*.2)*.055){const snow=B.Color3.FromHexString('#e5e9e5');col[v*4]=snow.r;col[v*4+1]=snow.g;col[v*4+2]=snow.b;}}const mesh=new B.Mesh(name,scene),v=new B.VertexData();Object.assign(v,{positions:p,indices:ind,normals:nm,colors:col,uvs:uv});v.applyToMesh(mesh);mesh.material=mountainMat;mesh.metadata={occluder:true};return mesh;}
 for(let i=0;i<13;i++)peak('distant Andes',-260+i*43,-250-rand()*60,35+rand()*51,35+rand()*21,i+10);
 peak('western massif',-112,-235,62,61,3);peak('eastern massif',100,-265,63,75,7);peak('granite base',-5,-278,51,72,2);
 peak('Torre Sur',-32,-275,85,17,3);peak('Torre Central',-7,-278,102,19,5);peak('Torre Norte',20,-279,80,16,8);
 const waterMat=mat('glacial turquoise','#448f99');waterMat.specularColor=new B.Color3(.9,.9,.7);waterMat.specularPower=140;waterMat.alpha=1;const water=B.MeshBuilder.CreateGround('lake',{width:420,height:400,subdivisions:18},scene);water.position.set(128,.85,-100);water.material=waterMat;water.isPickable=false;
 const animatedWater=software?null:lakeMaterial(scene);if(animatedWater)water.material=animatedWater;
 const buckets=new Map<B.Material,B.Mesh[]>();function batch(m:B.Mesh){if(!m.material)return;if(!m.isVerticesDataPresent('color'))m.setVerticesData('color',new Float32Array(m.getTotalVertices()*4).fill(1));const list=buckets.get(m.material)??[];list.push(m);buckets.set(m.material,list);}
 for(let i=0;i<(software?70:230);i++){const x=-110+rand()*155,z=55-rand()*190;if(height(x,z)<1.4||distanceToTrail({x,z})<4.1)continue;const size=.35+rand()*2.4;const rock=B.MeshBuilder.CreateIcoSphere('granite',{radius:1,subdivisions:software||mobile?1:2},scene);rock.position.set(x,height(x,z)+size*.24,z);rock.scaling.set(size,size*.62,size*.85);rock.rotation.set(rand(),rand()*6,rand());rock.material=mats.rock;batch(rock);if(x>-43&&x<7&&z>-58&&z<43){blockers.push({x,z,r:size*.7});}}
 function tree(x:number,z:number,size:number){const y=height(x,z);const trunk=B.MeshBuilder.CreateCylinder('lenga trunk',{height:size*2.2,diameterTop:.16*size,diameterBottom:.25*size,tessellation:7},scene);trunk.position.set(x,y+size,z);trunk.rotation.z=.13;trunk.material=mats.bark;batch(trunk);for(let j=0;j<(software||mobile?7:12);j++){const a=j*2.4;const leaf=ell('windswept crown',[x+Math.cos(a)*size*(.45+j*.035)-size*.24,y+size*(1.85+(j%4)*.22),z+Math.sin(a)*size*.62],[size*(.7+(j%3)*.12),size*.56,size*.85],j%2?mats.leaf:mats.leaf2);leaf.rotation.z=Math.sin(j*4)*.35;const crown=foliageCluster(scene,'lenga foliage',leaf.position,leaf.scaling,leaf.material!,foliageSeed(x,z,j),software||mobile);leaf.scaling.scaleInPlace(.76);batch(leaf);batch(crown);if(j%3===0){const branch=B.MeshBuilder.CreateTube("lenga branch",{path:[new B.Vector3(x,y+size,z),leaf.position.clone()],radius:size*.045,tessellation:5},scene);branch.material=mats.bark;batch(branch);}}if(x>-43&&x<7&&z>-58&&z<43)blockers.push({x,z,r:size*.25+.25});}
 tree(-17,33,3);tree(-24,22,2.5);tree(-34,3,2.2);tree(-27,-32,1.9);
 for(let i=0;i<(software?12:32);i++){const x=-95+rand()*87,z=45-rand()*145;if(distanceToTrail({x,z})>7)tree(x,z,1+rand()*1.5);}
 for(let i=0;i<(software?80:340);i++){const x=-90+rand()*115,z=48-rand()*155;if(height(x,z)<1.6||distanceToTrail({x,z})<2.4)continue;const size=.45+rand()*.8;batch(ell('low shrub',[x,height(x,z)+size*.4,z],[size*1.4,size*.9,size],i%3?mats.leaf:mats.leaf2));}
 buckets.forEach((meshes,material)=>{if(!meshes.length)return;const merged=B.Mesh.MergeMeshes(meshes,true,true,undefined,false,false);if(merged){merged.material=material;merged.receiveShadows=true;merged.metadata={occluder:true};if(material===mats.bark||material===mats.rock)shadow.addShadowCaster(merged);}});
 // Thousands of individual grass blades batched into one draw call.
 const gp:number[]=[],gi:number[]=[],gc:number[]=[];for(let i=0;i<(software?450:mobile?2800:10500);i++){const x=-65+rand()*78,z=47-rand()*132;if(height(x,z)<1.5||distanceToTrail({x,z})<1.7)continue;const y=height(x,z),h=.18+rand()*.63;for(let b=0;b<3;b++){const a=rand()*Math.PI*2,w=.035+rand()*.045,dx=Math.cos(a)*w,dz=Math.sin(a)*w,id=gp.length/3;gp.push(x-dx,y,z-dz,x+dx,y,z+dz,x+Math.cos(a+.8)*h*.27,y+h,z+Math.sin(a+.8)*h*.27);gi.push(id,id+1,id+2);const c=B.Color3.FromHexString(b%2?'#bbae70':'#9e995b').scale(.85+rand()*.35);for(let v=0;v<3;v++)gc.push(c.r,c.g,c.b,1);}}
 const gn:number[]=[];B.VertexData.ComputeNormals(gp,gi,gn);const grass=new B.Mesh('golden grasses',scene),gvd=new B.VertexData();Object.assign(gvd,{positions:gp,indices:gi,normals:gn,colors:gc});gvd.applyToMesh(grass);const grassMat=mat('grass','#ffffff');grassMat.backFaceCulling=false;grass.material=grassMat;grass.isPickable=false;const windyGrass=software?null:grassMaterial(scene);if(windyGrass)grass.material=windyGrass;
 function sign(x:number,z:number,label:string){const y=height(x,z);const post=box('trail sign post',[x,y+1.1,z],[.16,2.2,.16],mats.bark);const board=box('trail sign',[x,y+1.95,z],[2.2,.62,.12],mats.bark);const texture=new B.DynamicTexture('sign lettering',{width:512,height:160},scene,false);const ctx=texture.getContext();ctx.fillStyle='#574931';ctx.fillRect(0,0,512,160);ctx.fillStyle='#f5ebc8';ctx.font='bold 42px sans-serif';ctx.fillText(label,25,94);texture.update();const front=B.MeshBuilder.CreatePlane('sign text',{width:2.16,height:.6},scene);front.position.set(x,y+1.95,z+.065);front.rotation.y=Math.PI;const textMat=mat('sign ink','#ffffff');textMat.diffuseTexture=texture;textMat.backFaceCulling=false;front.material=textMat;front.isPickable=false;front.metadata={label};shadow.addShadowCaster(post);shadow.addShadowCaster(board);}
 sign(-13.7,28,'MIRADOR  ↑');sign(-18.4,5,'MIRADOR');sign(-5.6,-34,'EL LAGO');
 const wildlife:{root:B.TransformNode;home:Point;neck:B.TransformNode;legs:B.TransformNode[];focus:B.TransformNode;state:WildlifeState;phase:number;motion:number}[]=[];
 function guanaco(x:number,z:number,scale:number){const root=new B.TransformNode('guanaco',scene);root.position.set(x,height(x,z),z);root.scaling.setAll(scale);root.rotation.y=.65;
 ell('guanaco torso',[0,1.17,0],[.63,.70,1.5],mats.brown,root);ell('guanaco belly',[0,1.,-.03],[.51,.34,1.27],mats.cream,root);ell('guanaco chest',[0,1.22,-.51],[.52,.67,.48],mats.cream,root);
 const neck=new B.TransformNode('articulated neck',scene);neck.parent=root;neck.position.set(0,1.35,-.51);ell('long neck',[0,.4,-.07],[.31,.99,.35],mats.brown,neck);ell('light throat',[0,.37,-.23],[.205,.81,.11],mats.cream,neck);ell('guanaco head',[0,.96,-.16],[.265,.29,.49],mats.brown,neck);ell('guanaco muzzle',[0,.905,-.405],[.20,.17,.31],mats.animalNose,neck);
 for(const side of [-1,1]){ell('guanaco ears',[side*.105,1.22,-.065],[.09,.32,.105],mats.brown,neck);ell('guanaco eye',[side*.145,1.01,-.2],[.045,.059,.065],mats.eye,neck);ell('guanaco ear interior',[side*.105,1.23,-.116],[.037,.23,.025],mats.cream,neck);ell('guanaco eye glint',[side*.162,1.025,-.215],[.012,.012,.016],mats.helmet,neck);}
 const animalLegs:B.TransformNode[]=[];for(const side of [-1,1])for(const front of [-1,1]){const leg=new B.TransformNode('guanaco leg rig',scene);leg.parent=root;leg.position.set(side*.22,.99,front*.47);ell('guanaco upper leg',[0,-.2,0],[.16,.47,.2],mats.brown,leg);ell('guanaco lower leg',[0,-.65,.018],[.09,.48,.12],mats.cream,leg);ell('guanaco hoof',[0,-.91,-.04],[.14,.15,.21],mats.boots,leg);animalLegs.push(leg);}
 ell('guanaco tail',[0,1.38,.74],[.13,.16,.37],mats.brown,root);const focus=new B.TransformNode('photography anchor',scene);focus.parent=root;focus.position.set(0,1.2,-.12);
 furTufts(scene,root,new B.Vector3(0,1.17,0),new B.Vector3(.32,.35,.75),software?85:mobile?240:750,'#a97a4e','guanaco coat detail');
 root.getChildMeshes().forEach(m=>{m.metadata={animal:true};cast(m);});wildlife.push({root,home:{x,z},neck,legs:animalLegs,focus,state:'grazing',phase:wildlife.length*2.3,motion:0});return root;}
 const animals=[guanaco(-18,-17,1),guanaco(-21,-20,.8)];
 function animalFocus(root:B.TransformNode){const focus=wildlife.find(a=>a.root===root)!.focus;root.computeWorldMatrix(true);focus.computeWorldMatrix(true);return focus.getAbsolutePosition().clone();}
 const rubbish=litter.map((p,i)=>{const root=new B.TransformNode('litter '+i,scene);root.position.set(p.x,height(p.x,p.z)+.14,p.z);const m=i===1?box('discarded carton',[0,0,0],[.38,.25,.3],mats.helmet,root):ell('discarded bottle',[0,0,0],[.18,.19,.55],i?mats.gold:mats.helmet,root);m.rotation.y=.7;m.isPickable=false;return root;});
 const markers=discoveries.map(d=>{const ring=B.MeshBuilder.CreateTorus('discovery ring',{diameter:2.5,thickness:.045,tessellation:36},scene);ring.position.set(d.x,height(d.x,d.z)+.1,d.z);const m=mat('waypoint glow','#f2cd78');m.emissiveColor=B.Color3.FromHexString('#b59c60');ring.material=m;ring.isPickable=false;return ring;});
 const bird=new B.TransformNode('condor',scene);ell('condor body',[0,0,0],[.35,.3,1.1],mats.nose,bird);const wing1=ell('left wing',[-.85,0,0],[1.8,.07,.65],mats.nose,bird),wing2=ell('right wing',[.85,0,0],[1.8,.07,.65],mats.nose,bird);bird.getChildMeshes().forEach(m=>m.isPickable=false);
 let isNight=false;
 function night(value:boolean){isNight=value;scene.environmentIntensity=value?.09:.55;hemi.intensity=value?.38:.66;sun.intensity=value?.38:1.45;sun.diffuse=value?new B.Color3(.56,.67,1):new B.Color3(1,.88,.65);scene.fogColor=value?new B.Color3(.06,.095,.15):new B.Color3(.65,.77,.79);skyMat.setFloat('night',value?1:0);}
 let gaitPhase=0,walkBlend=0;let lastPlayer:Point|null=null;
 function animate(time:number,_speed:number,dt:number){skyMat.setFloat('time',time);if(windyGrass){windyGrass.setFloat('time',time);windyGrass.setFloat('night',isNight?1:0);windyGrass.setVector3('cameraPosition',camera.position);}if(animatedWater){animatedWater.setFloat('time',time);animatedWater.setFloat('night',isNight?1:0);animatedWater.setVector3('cameraPosition',camera.position);}const p={x:player.position.x,z:player.position.z};const moved=lastPlayer?Math.min(.6,distance(p,lastPlayer)):0;lastPlayer=p;gaitPhase+=moved*2.5;walkBlend+=(moved>.002?1-walkBlend:-walkBlend)*Math.min(1,dt*9);const walk=Math.sin(gaitPhase)*walkBlend;
 legs[0].rotation.x=walk*.5;legs[1].rotation.x=-walk*.5;knees[0].rotation.x=-Math.max(0,-walk)*.48;knees[1].rotation.x=-Math.max(0,walk)*.48;arms[0].rotation.x=-walk*.4;arms[1].rotation.x=walk*.4;body.position.y=Math.abs(Math.sin(gaitPhase))*walkBlend*.03+Math.sin(time*1.8)*.009;body.rotation.z=walk*.018;headRig.rotation.y=Math.sin(time*.55)*.075*(1-walkBlend);headRig.rotation.x=Math.sin(gaitPhase)*walkBlend*.025;const blink=time%5.7;lids.forEach(l=>l.scaling.y=blink<.15?.19:.015);
 for(const animal of wildlife){const before=animal.root.position.clone();const result=wildlifeStep(before,animal.home,p,animal.state,dt,q=>canWalk(q)&&!blockers.some(b=>distance(q,b)<b.r+.55));animal.state=result.state;animal.root.position.set(result.position.x,height(result.position.x,result.position.z),result.position.z);const dx=result.position.x-before.x,dz=result.position.z-before.z,walking=Math.hypot(dx,dz)>.0001;if(walking){const angle=Math.atan2(-dx,-dz);animal.root.rotation.y+=Math.atan2(Math.sin(angle-animal.root.rotation.y),Math.cos(angle-animal.root.rotation.y))*Math.min(1,dt*3);animal.motion+=Math.hypot(dx,dz)*8;}
 const grazing=animal.state==='grazing';const bend=grazing?-1.85+Math.sin(time*.8+animal.phase)*.14:0;animal.neck.rotation.x+=(bend-animal.neck.rotation.x)*Math.min(1,dt*2);animal.neck.rotation.y=grazing?Math.sin(time*.35+animal.phase)*.12:Math.max(-.55,Math.min(.55,Math.atan2(animal.root.position.x-p.x,animal.root.position.z-p.z)-animal.root.rotation.y));animal.legs.forEach((l,i)=>{const target=walking?Math.sin(animal.motion+(i===0||i===3?0:Math.PI))*.24:0;l.rotation.x+=(target-l.rotation.x)*Math.min(1,dt*10);});}
 bird.position.set(Math.sin(time*.065)*45-10,30+Math.sin(time*.2)*2,-65+Math.cos(time*.065)*25);bird.rotation.y=-time*.065;wing1.rotation.z=Math.sin(time*1.6)*.08;wing2.rotation.z=-wing1.rotation.z;}
 const textures={nose:surface(scene,'nose pores',5,42),rock:surface(scene,'granite grain',6,50),earth:surface(scene,'steppe detail',65,35),cloth:surface(scene,'woven cloth',5,28),wood:surface(scene,'bark grain',4,46),fur:furSurface(scene,'golden fur fibers',3),undercoat:furSurface(scene,'guanaco fibers',4)};
 const textured=new Map<B.StandardMaterial,typeof textures.rock>([[mats.nose,textures.nose],[mats.rock,textures.rock],[mountainMat,textures.rock],[groundMat,textures.earth],[mats.shirt,textures.cloth],[mats.pants,textures.cloth],[mats.pack,textures.cloth],[mats.bark,textures.wood],[mats.gloves,textures.cloth],[mats.fur,textures.fur],[mats.muzzle,textures.fur],[mats.brown,textures.undercoat],[mats.cream,textures.undercoat],[mats.pocket,textures.cloth]]);
 textured.forEach((detail,material)=>{if(!software){material.diffuseTexture=detail.texture;material.bumpTexture=detail.bump;}});
 if(!software){for(const original of [mats.eye,mats.nose,mats.cream,mats.animalNose,mats.pocket,mats.hardhat,mats.gloves,mats.brown,mats.fur,mats.muzzle,mats.shirt,mats.pants,mats.boots,mats.helmet,mats.pack,mats.strap,mats.rock,mats.bark,mountainMat,groundMat]){const pbr=new B.PBRMaterial(original.name+' physical',scene);pbr.albedoColor=original.diffuseColor.clone();pbr.metallic=0;pbr.roughness=original===mats.eye?.16:original===mats.nose?.56:original===mats.hardhat?.42:original===mats.boots?.72:.96;pbr.albedoTexture=original.diffuseTexture;pbr.bumpTexture=original.bumpTexture;pbr.backFaceCulling=original.backFaceCulling;pbr.directIntensity=1.1;pbr.environmentIntensity=.65;if(original===mats.eye){pbr.clearCoat.isEnabled=true;pbr.clearCoat.intensity=.6;pbr.clearCoat.roughness=.12;}scene.meshes.forEach(mesh=>{if(mesh.material===original)mesh.material=pbr;});}}
 if(!software)skyEnvironment(scene);
 const quality=cinematicPipeline(scene,camera,software,mobile);
 const fallback=software?softwareRenderer(canvas,scene,(w,h)=>{fallbackSize.renderWidth=w;fallbackSize.renderHeight=h;}):null;
 for(const m of scene.meshes)if(!m.parent&&m.name!=='sky'&&m.name!=='ripple')m.freezeWorldMatrix();
 function render(){scene.render();fallback?.(isNight);}
 return {engine,scene,camera,player,animals,rubbish,markers,blockers,night,animate,shadow,render,software,mobile,quality,animalFocus};
}
