import * as B from './babylon';
import {softwareRenderer} from './software';
import {height,distanceToTrail,trail,litter,discoveries,type Point} from './rules';
export {B};
export function makeWorld(canvas:HTMLCanvasElement){
 let software=false;let engine:B.Engine;const fallbackSize={renderWidth:canvas.clientWidth,renderHeight:canvas.clientHeight,textureSize:512,deterministicLockstep:false,lockstepMaxSteps:4};try{engine=new B.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true,antialias:true},true);}catch{software=true;engine=new B.NullEngine(fallbackSize);}engine.setHardwareScalingLevel(Math.max(1,window.devicePixelRatio/1.5));
 const scene=new B.Scene(engine);scene.useRightHandedSystem=true;scene.clearColor=new B.Color4(.58,.76,.85,1);scene.fogMode=B.Scene.FOGMODE_EXP2;scene.fogDensity=.0026;scene.fogColor=new B.Color3(.65,.77,.79);scene.skipPointerMovePicking=true;
 const camera=new B.FreeCamera('explorer camera',new B.Vector3(-5,10,43),scene);camera.minZ=.15;camera.maxZ=800;camera.fov=.88;camera.inputs.clear();scene.activeCamera=camera;
 const hemi=new B.HemisphericLight('sky light',new B.Vector3(0,1,0),scene);hemi.intensity=.78;hemi.groundColor=new B.Color3(.32,.29,.2);
 const sun=new B.DirectionalLight('late afternoon sun',new B.Vector3(.6,-1,.35),scene);sun.position=new B.Vector3(-90,140,-80);sun.intensity=1.65;sun.diffuse=new B.Color3(1,.88,.65);
 const shadow=new B.ShadowGenerator(1024,sun);shadow.useBlurExponentialShadowMap=true;shadow.blurKernel=12;shadow.darkness=.25;sun.shadowMinZ=1;sun.shadowMaxZ=270;
 const blockers:{x:number;z:number;r:number}[]=[];
 function mat(name:string,color:string){const m=new B.StandardMaterial(name,scene);m.diffuseColor=B.Color3.FromHexString(color);m.specularColor=new B.Color3(.05,.05,.04);return m;}
 const mats={fur:mat('warm brown fur','#a56d3e'),muzzle:mat('cream muzzle','#d8ab68'),nose:mat('nose and eyes','#242522'),shirt:mat('golden ranger shirt','#e6b72f'),pants:mat('forest green trousers','#455e3d'),boots:mat('leather boots','#4d3827'),helmet:mat('ivory ranger helmet','#eee8d6'),pack:mat('canvas backpack','#7a7558'),strap:mat('canvas straps','#4c4b34'),leaf:mat('lenga green','#657442'),leaf2:mat('lenga light','#8c9350'),bark:mat('weathered wood','#5f4c32'),rock:mat('granite boulders','#81816f'),white:mat('snow','#e5e9e3'),gold:mat('discovery gold','#f0cf73'),brown:mat('guanaco fur','#a97a4e')};
 function ell(name:string,pos:number[],scale:number[],material:B.Material,parent?:B.TransformNode){const m=B.MeshBuilder.CreateSphere(name,{diameter:1,segments:software?6:12},scene);m.position.set(pos[0],pos[1],pos[2]);m.scaling.set(scale[0],scale[1],scale[2]);m.material=material;m.parent=parent??null;return m;}
 function box(name:string,pos:number[],scale:number[],material:B.Material,parent?:B.TransformNode){const m=B.MeshBuilder.CreateBox(name,{size:1},scene);m.position.set(...pos as [number,number,number]);m.scaling.set(...scale as [number,number,number]);m.material=material;m.parent=parent??null;return m;}
 const player=new B.TransformNode('Forestín',scene);const body=new B.TransformNode('walking body',scene);body.parent=player;
 ell('shirt',[0,1.24,0],[.89,1,.64],mats.shirt,body);ell('trousers',[0,.79,0],[.78,.45,.58],mats.pants,body);
 ell('head',[0,1.99,.04],[.88,.82,.75],mats.fur,body);ell('muzzle',[0,1.85,-.38],[.62,.43,.36],mats.muzzle,body);ell('nose',[0,1.99,-.575],[.19,.13,.13],mats.nose,body);
 for(const side of [-1,1]){ell('ear',[side*.4,2.12,0],[.24,.28,.17],mats.fur,body);ell('ear inner',[side*.4,2.12,-.07],[.13,.16,.05],mats.boots,body);ell('eye white',[side*.22,2.1,-.29],[.17,.2,.13],mats.helmet,body);ell('eye',[side*.22,2.11,-.355],[.09,.12,.055],mats.nose,body);box('tooth',[side*.048,1.72,-.534],[.082,.13,.05],mats.helmet,body);box('backpack strap',[side*.29,1.39,-.26],[.11,.68,.1],mats.strap,body);}
 ell('helmet dome',[0,2.3,0],[1.02,.52,.91],mats.helmet,body);ell('helmet brim',[0,2.2,-.095],[1.18,.09,1.06],mats.helmet,body);box('helmet badge',[0,2.39,-.431],[.18,.18,.035],mats.pants,body);
 box('backpack',[0,1.34,.43],[.69,.73,.29],mats.pack,body);box('backpack pocket',[0,1.16,.6],[.45,.3,.09],mats.strap,body);box('pack patch',[0,1.51,.59],[.18,.19,.018],mats.helmet,body);
 const legs:B.TransformNode[]=[],arms:B.TransformNode[]=[];
 for(const side of [-1,1]){const leg=new B.TransformNode('leg',scene);leg.parent=body;leg.position.set(side*.22,.83,0);ell('trouser leg',[0,-.22,0],[.37,.62,.42],mats.pants,leg);ell('boot',[0,-.62,-.09],[.38,.28,.59],mats.boots,leg);legs.push(leg);const arm=new B.TransformNode('arm',scene);arm.parent=body;arm.position.set(side*.48,1.62,0);ell('sleeve',[0,-.21,0],[.34,.56,.35],mats.shirt,arm);ell('paw',[0,-.5,-.025],[.25,.31,.25],mats.fur,arm);arms.push(arm);}
 const tail=ell('coipo tail',[0,.5,.64],[.18,.17,1.03],mats.fur,body);tail.rotation.x=.22;
 player.getChildMeshes().forEach(m=>{shadow.addShadowCaster(m);m.isPickable=false;});
 // Sky is a real shader sphere, with soft procedural cloud layers.
 B.Effect.ShadersStore['paineSkyVertexShader']='precision highp float;attribute vec3 position;uniform mat4 worldViewProjection;varying vec3 vPosition;void main(){vPosition=position;gl_Position=worldViewProjection*vec4(position,1.0);}';
 B.Effect.ShadersStore['paineSkyFragmentShader']=`precision highp float;varying vec3 vPosition;uniform float night;float hash(vec2 p){return fract(sin(dot(p,vec2(127.1,311.7)))*43758.5453);}float noise(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(hash(i),hash(i+vec2(1,0)),f.x),mix(hash(i+vec2(0,1)),hash(i+vec2(1,1)),f.x),f.y);}void main(){vec3 d=normalize(vPosition);float h=max(d.y,0.);vec3 col=mix(vec3(.81,.86,.8),vec3(.27,.57,.82),pow(h,.45));vec2 p=d.xz/max(.12,d.y)*2.8;float n=noise(p)*.58+noise(p*2.1)*.26+noise(p*4.3)*.16;float cloud=smoothstep(.52,.72,n)*smoothstep(.03,.28,h);col=mix(col,vec3(.98,.95,.86),cloud*.9);float glow=pow(max(0.,dot(d,normalize(vec3(-.6,.48,-.5)))),40.);col+=vec3(.32,.21,.09)*glow;col=mix(col,vec3(.025,.048,.09)+col*.07,night);float stars=step(.9975,hash(floor(d.xz/max(.05,d.y)*700.)))*smoothstep(.15,.4,h);col+=stars*night*.8;gl_FragColor=vec4(col,1.);}`;
 const skyMat=new B.ShaderMaterial('Patagonian sky',scene,{vertex:'paineSky',fragment:'paineSky'},{attributes:['position'],uniforms:['worldViewProjection','night']});skyMat.backFaceCulling=false;skyMat.setFloat('night',0);skyMat.disableDepthWrite=true;const sky=B.MeshBuilder.CreateSphere('sky',{diameter:1200,segments:24},scene);sky.material=skyMat;sky.isPickable=false;sky.infiniteDistance=true;
 let seed=134;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}
 // Shared analytical height field keeps feet, trail and terrain aligned.
 const positions:number[]=[],indices:number[]=[],colors:number[]=[];const nx=software?45:180,nz=software?50:200;
 for(let j=0;j<=nz;j++)for(let i=0;i<=nx;i++){const x=-180+i*(360/nx),z=-300+j*(400/nz);const y=height(x,z);positions.push(x,y,z);const d=distanceToTrail({x,z});const tint=rand()*.1+Math.sin(x*.31+z*.2)*.04;let c=B.Color3.FromHexString(d<1.6?'#c4b28b':d<2.1?'#a6a077':'#929365');if(y<1.6)c=B.Color3.FromHexString('#97977f');c=c.scale(1+tint);colors.push(c.r,c.g,c.b,1);}
 for(let j=0;j<nz;j++)for(let i=0;i<nx;i++){const a=j*(nx+1)+i;indices.push(a,a+nx+1,a+1,a+1,a+nx+1,a+nx+2);}
 const normals:number[]=[];B.VertexData.ComputeNormals(positions,indices,normals,{useRightHandedSystem:true});const ground=new B.Mesh('rolling Patagonian steppe',scene);const vd=new B.VertexData();Object.assign(vd,{positions,indices,normals,colors});vd.applyToMesh(ground);const groundMat=mat('meadow','#ffffff');groundMat.backFaceCulling=false;ground.material=groundMat;ground.receiveShadows=true;ground.metadata={occluder:true};
 // Build a smooth narrow ribbon along the actual route.
 const paths:B.Vector3[][]=[[],[]];for(let n=0;n<trail.length-1;n++){const a=trail[n],b=trail[n+1],len=Math.hypot(b.x-a.x,b.z-a.z),px=-(b.z-a.z)/len,pz=(b.x-a.x)/len;for(let t=0;t<1;t+=.055){const x=a.x+(b.x-a.x)*t,z=a.z+(b.z-a.z)*t;for(let s=0;s<2;s++){const sign=s?1:-1,xx=x+px*1.35*sign,zz=z+pz*1.35*sign;paths[s].push(new B.Vector3(xx,height(xx,zz)+(software?.32:.07),zz));}}}
 const path=B.MeshBuilder.CreateRibbon('winding trail',{pathArray:paths,sideOrientation:B.Mesh.DOUBLESIDE},scene);path.material=mat('sandy trail','#bca884');path.receiveShadows=true;path.isPickable=false;
 // Rock spires: irregular radial ridges, not cones.
 function peak(name:string,x:number,z:number,h:number,r:number,salt:number){const p:number[]=[],ind:number[]=[],col:number[]=[],segments=15,rings=10;const phase=salt*.71;
 for(let k=0;k<=rings;k++){const t=k/rings;for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2;const ridge=1+Math.sin(i*7.1+salt)*.23+Math.cos(k*2+i)*.11;const radius=r*Math.pow(1-t,.6)*ridge+(k===rings?0.1:0);p.push(x+Math.cos(a)*radius+Math.sin(t*4+phase)*r*.15,h*t-1,z+Math.sin(a)*radius);const snow=(t>.42&&t<.77&&Math.sin(a*3+salt)+Math.cos(t*24)>.7)||t>.95;const shade=.82+rand()*.2;const c=B.Color3.FromHexString(snow?'#e3e8e2':t>.78?'#a0a2a1':t>.3?'#778387':'#777e72').scale(shade);col.push(c.r,c.g,c.b,1);}}
 for(let k=0;k<rings;k++)for(let i=0;i<segments;i++){const a=k*segments+i,b=k*segments+(i+1)%segments;ind.push(a,b,a+segments,b,b+segments,a+segments);}const nm:number[]=[];B.VertexData.ComputeNormals(p,ind,nm);const mesh=new B.Mesh(name,scene),v=new B.VertexData();Object.assign(v,{positions:p,indices:ind,normals:nm,colors:col});v.applyToMesh(mesh);mesh.material=groundMat;mesh.convertToFlatShadedMesh();mesh.metadata={occluder:true};return mesh;}
 for(let i=0;i<13;i++)peak('distant Andes',-260+i*43,-250-rand()*60,35+rand()*51,35+rand()*21,i+10);
 peak('western massif',-112,-235,62,61,3);peak('eastern massif',100,-265,63,75,7);peak('granite base',-5,-278,51,72,2);
 peak('Torre Sur',-32,-275,85,17,3);peak('Torre Central',-7,-278,102,19,5);peak('Torre Norte',20,-279,80,16,8);
 const waterMat=mat('glacial turquoise','#448f99');waterMat.specularColor=new B.Color3(.9,.9,.7);waterMat.specularPower=140;waterMat.alpha=.94;const water=B.MeshBuilder.CreateGround('lake',{width:420,height:400,subdivisions:18},scene);water.position.set(128,.85,-100);water.material=waterMat;water.isPickable=false;
 const rippleMat=mat('water glints','#a4c9bd');rippleMat.alpha=.26;for(let i=0;i<44;i++){const x=16+rand()*155,z=30-rand()*200;if(height(x,z)>1)continue;const line=B.MeshBuilder.CreateGround('ripple',{width:2+rand()*12,height:.04+rand()*.07},scene);line.position.set(x,.87+rand()*.02,z);line.material=rippleMat;line.isPickable=false;}
 const buckets=new Map<B.Material,B.Mesh[]>();function batch(m:B.Mesh){if(!m.material)return;const list=buckets.get(m.material)??[];list.push(m);buckets.set(m.material,list);}
 for(let i=0;i<(software?70:230);i++){const x=-110+rand()*155,z=55-rand()*190;if(height(x,z)<1.4||distanceToTrail({x,z})<4.1)continue;const size=.35+rand()*2.4;const rock=B.MeshBuilder.CreateIcoSphere('granite',{radius:1,subdivisions:1},scene);rock.position.set(x,height(x,z)+size*.24,z);rock.scaling.set(size,size*.62,size*.85);rock.rotation.set(rand(),rand()*6,rand());rock.material=mats.rock;batch(rock);if(x>-43&&x<7&&z>-58&&z<43){blockers.push({x,z,r:size*.7});}}
 function tree(x:number,z:number,size:number){const y=height(x,z);const trunk=B.MeshBuilder.CreateCylinder('lenga trunk',{height:size*2.2,diameterTop:.16*size,diameterBottom:.25*size,tessellation:7},scene);trunk.position.set(x,y+size,z);trunk.rotation.z=.13;trunk.material=mats.bark;batch(trunk);for(let j=0;j<5;j++){const a=j*2.4;const leaf=ell('windswept crown',[x+Math.cos(a)*size*.65,y+size*(1.9+j*.16),z+Math.sin(a)*size*.6],[size*1.8,size*.95,size*1.5],j%2?mats.leaf:mats.leaf2);batch(leaf);}if(x>-43&&x<7&&z>-58&&z<43)blockers.push({x,z,r:size*.25+.25});}
 tree(-17,33,3);tree(-24,22,2.5);tree(-34,3,2.2);tree(-27,-32,1.9);
 for(let i=0;i<(software?12:32);i++){const x=-95+rand()*87,z=45-rand()*145;if(distanceToTrail({x,z})>7)tree(x,z,1+rand()*1.5);}
 for(let i=0;i<(software?80:340);i++){const x=-90+rand()*115,z=48-rand()*155;if(height(x,z)<1.6||distanceToTrail({x,z})<2.4)continue;const size=.45+rand()*.8;batch(ell('low shrub',[x,height(x,z)+size*.4,z],[size*1.4,size*.9,size],i%3?mats.leaf:mats.leaf2));}
 buckets.forEach((meshes,material)=>{if(!meshes.length)return;const merged=B.Mesh.MergeMeshes(meshes,true,true,undefined,false,false);if(merged){merged.material=material;merged.receiveShadows=true;merged.metadata={occluder:true};if(material===mats.bark||material===mats.rock)shadow.addShadowCaster(merged);}});
 // Thousands of individual grass blades batched into one draw call.
 const gp:number[]=[],gi:number[]=[],gc:number[]=[];for(let i=0;i<(software?450:10500);i++){const x=-65+rand()*78,z=47-rand()*132;if(height(x,z)<1.5||distanceToTrail({x,z})<1.7)continue;const y=height(x,z),h=.18+rand()*.63;for(let b=0;b<3;b++){const a=rand()*Math.PI*2,w=.035+rand()*.045,dx=Math.cos(a)*w,dz=Math.sin(a)*w,id=gp.length/3;gp.push(x-dx,y,z-dz,x+dx,y,z+dz,x+Math.cos(a+.8)*h*.27,y+h,z+Math.sin(a+.8)*h*.27);gi.push(id,id+1,id+2);const c=B.Color3.FromHexString(b%2?'#bbae70':'#9e995b').scale(.85+rand()*.35);for(let v=0;v<3;v++)gc.push(c.r,c.g,c.b,1);}}
 const gn:number[]=[];B.VertexData.ComputeNormals(gp,gi,gn);const grass=new B.Mesh('golden grasses',scene),gvd=new B.VertexData();Object.assign(gvd,{positions:gp,indices:gi,normals:gn,colors:gc});gvd.applyToMesh(grass);const grassMat=mat('grass','#ffffff');grassMat.backFaceCulling=false;grass.material=grassMat;grass.isPickable=false;
 function sign(x:number,z:number,label:string){const y=height(x,z);const post=box('trail sign post',[x,y+1.1,z],[.16,2.2,.16],mats.bark);const board=box('trail sign',[x,y+1.95,z],[2.2,.62,.12],mats.bark);const texture=new B.DynamicTexture('sign lettering',{width:512,height:160},scene,false);const ctx=texture.getContext();ctx.fillStyle='#574931';ctx.fillRect(0,0,512,160);ctx.fillStyle='#f5ebc8';ctx.font='bold 42px sans-serif';ctx.fillText(label,25,94);texture.update();const front=B.MeshBuilder.CreatePlane('sign text',{width:2.16,height:.6},scene);front.position.set(x,y+1.95,z+.065);front.rotation.y=Math.PI;const textMat=mat('sign ink','#ffffff');textMat.diffuseTexture=texture;textMat.backFaceCulling=false;front.material=textMat;front.isPickable=false;front.metadata={label};shadow.addShadowCaster(post);shadow.addShadowCaster(board);}
 sign(-13.7,28,'MIRADOR  ↑');sign(-18.4,5,'MIRADOR');sign(-5.6,-34,'EL LAGO');
 function guanaco(x:number,z:number,scale:number){const root=new B.TransformNode('guanaco',scene);root.position.set(x,height(x,z),z);root.scaling.setAll(scale);root.rotation.y=.65;ell('guanaco torso',[0,1.05,0],[.67,.75,1.38],mats.brown,root);ell('guanaco belly',[0,.92,-.15],[.57,.44,1],mats.muzzle,root);ell('long neck',[0,1.69,-.5],[.33,1.25,.4],mats.brown,root);ell('guanaco head',[0,2.34,-.64],[.34,.4,.56],mats.brown,root);ell('guanaco muzzle',[0,2.28,-.9],[.28,.22,.3],mats.muzzle,root);for(const s of [-1,1]){ell('guanaco ears',[s*.12,2.69,-.59],[.11,.45,.14],mats.brown,root);ell('guanaco eye',[s*.16,2.4,-.71],[.05,.07,.08],mats.nose,root);for(const k of [-1,1]){ell('guanaco leg',[s*.22,.49,k*.44],[.13,1.03,.16],mats.brown,root);ell('guanaco hoof',[s*.22,.08,k*.44],[.16,.16,.23],mats.boots,root);}}ell('guanaco tail',[0,1.34,.76],[.13,.18,.44],mats.brown,root);root.getChildMeshes().forEach(m=>{m.metadata={animal:true};shadow.addShadowCaster(m);});return root;}
 const animals=[guanaco(-18,-17,1),guanaco(-21,-20,.8)];
 const rubbish=litter.map((p,i)=>{const root=new B.TransformNode('litter '+i,scene);root.position.set(p.x,height(p.x,p.z)+.14,p.z);const m=i===1?box('discarded carton',[0,0,0],[.38,.25,.3],mats.helmet,root):ell('discarded bottle',[0,0,0],[.18,.19,.55],i?mats.gold:mats.helmet,root);m.rotation.y=.7;m.isPickable=false;return root;});
 const markers=discoveries.map(d=>{const ring=B.MeshBuilder.CreateTorus('discovery ring',{diameter:2.5,thickness:.045,tessellation:36},scene);ring.position.set(d.x,height(d.x,d.z)+.1,d.z);const m=mat('waypoint glow','#f2cd78');m.emissiveColor=B.Color3.FromHexString('#b59c60');ring.material=m;ring.isPickable=false;return ring;});
 const bird=new B.TransformNode('condor',scene);ell('condor body',[0,0,0],[.35,.3,1.1],mats.nose,bird);const wing1=ell('left wing',[-.85,0,0],[1.8,.07,.65],mats.nose,bird),wing2=ell('right wing',[.85,0,0],[1.8,.07,.65],mats.nose,bird);bird.getChildMeshes().forEach(m=>m.isPickable=false);
 let isNight=false;
 function night(value:boolean){isNight=value;hemi.intensity=value?.38:.78;sun.intensity=value?.38:1.65;sun.diffuse=value?new B.Color3(.56,.67,1):new B.Color3(1,.88,.65);scene.fogColor=value?new B.Color3(.06,.095,.15):new B.Color3(.65,.77,.79);skyMat.setFloat('night',value?1:0);}
 function animate(time:number,speed:number){const walk=Math.sin(time*9)*speed;legs[0].rotation.x=walk*.55;legs[1].rotation.x=-walk*.55;arms[0].rotation.x=-walk*.45;arms[1].rotation.x=walk*.45;body.position.y=Math.abs(Math.sin(time*9))*speed*.055;bird.position.set(Math.sin(time*.065)*45-10,30+Math.sin(time*.2)*2,-65+Math.cos(time*.065)*25);bird.rotation.y=-time*.065;wing1.rotation.z=Math.sin(time*1.6)*.08;wing2.rotation.z=-wing1.rotation.z;}
 const fallback=software?softwareRenderer(canvas,scene,(w,h)=>{fallbackSize.renderWidth=w;fallbackSize.renderHeight=h;}):null;
 function render(){scene.render();fallback?.(isNight);}
 return {engine,scene,camera,player,animals,rubbish,markers,blockers,night,animate,shadow,render,software};
}
